作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [5]:
print(np.linalg.inv(array1))
A=np.linalg.inv(array1)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]


In [16]:
B =(A @ array1) #np.dot(A,array1)
print(B)

[[ 1.00000000e+00 -5.55111512e-17]
 [-1.11022302e-16  1.00000000e+00]]


In [15]:
B[0][0]==1
B[1][1]==1

True

In [ ]:
#2. 運用上列array計算特徵值、特徵向量?

In [23]:
w,v = np.linalg.eig(array1)

In [24]:
w

array([13.,  2.])

In [25]:
np.linalg.eigvals(array1)

array([13.,  2.])

In [21]:
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [ ]:
#3. 運用上列array計算SVD?

In [26]:
u,s,vh = np.linalg.svd(array1)

In [27]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [28]:
s

array([13.94721714,  1.86417116])

In [29]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])